---
- name: Install Nginx
  become: yes
  become_method: sudo
  yum: name=nginx state=present

- name: Change default nginx site
  become: yes
  become_method: sudo
  template: src={{ ws_template }} dest={{ ws_vhost_path }}/{{ ws_vhost_file }}
  notify: Restart nginx