---
- hosts: all
  become: yes
  become_method: sudo
  vars:
    web_server: nginx
    servername: jahia.local
    timezone: UTC
  vars_files:
    - vars/mysql.yml
    - vars/common.yml
    - vars/java.yml
    - vars/maven.yml
    - vars/jahia.yml
    - vars/tomcat.yml
    - [ "vars/nginx.yml", "vars/ws_defaults.yml" ]
    - vars/php.yml
    - vars/openldap.yml
    - vars/shibboleth.yml
  roles:
    - init
    - nginx
    - mysql
    - java
    - maven
    - jahia
    - marketing
    - forms
    - php
    - openldap
    - tomcat
    - shibboleth
    - mongodb
